### ISSUE TITLE
Still problems while trying to deploy to ubuntu server

### ISSUE THREAD

**Issue by misaelnieto** [collective/collective.hostout#5]
On the README file it says that all I need to do on the first time is to run `bin/hostout sitename bootstrap`. All I get is this:

```
$ bin/hostout mysite deploy
/home/tzicatl/Aplicaciones/Buildout/egss/pycrypto-2.3-py2.6-linux-x86_64.egg/Crypto/Util/randpool.py:40: RandomPool_DeprecationWarning: This application uses RandomPool, which is BROKEN in older releases.  See http://www.pycrypto.org/randpool-broken
RandomPool_DeprecationWarning)
Hostout: Running command 'deploy' from 'collective.hostout.fabfile'
Hostout: Running command 'predeploy' from 'hostout.supervisor.fabfile'
[adminuser@pruebas.mysite.org:22] sudo: sudo -S -p 'sudo password:'  /bin/bash -l -c "/opt/mysite_libros/bin/supervisorctl shutdown || echo 'Failed to shutdown'"
[adminuser@pruebas.mysite.org:22] err: /bin/bash: /opt/mysite_libros/bin/supervisorctl: No such file or directory
[adminuser@pruebas.mysite.org:22] out: Failed to shutdown
Hostout: Running command 'uploadeggs' from 'collective.hostout.fabfile'
[adminuser@pruebas.mysite.org:22] run: /bin/bash -l -c "ls /opt/buildout-cache/downloads/dist"
[adminuser@pruebas.mysite.org:22] err: ls: cannot access /opt/buildout-cache/downloads/dist: No such file or directory

Fatal error: run() encountered an error (return code 2) while executing 'ls /opt/buildout-cache/downloads/dist'

None


Aborting.
```

After that failed attempt I tryied the following commands:

```
bin/hostout mysite bootstrap_buildout_ubuntu
bin/hostout mysite bootstrap_python_ubuntu
bin/hostout mysite bootstrap_users
bin/hostout mysite buildout
bin/hostout mysite deploy
```

`buildout` and `deploy` commands fail.
For `buildout` the errors are:

```
$ bin/hostout mysite buildout
/home/tzicatl/Aplicaciones/Buildout/egss/pycrypto-2.3-py2.6-linux-x86_64.egg/Crypto/Util/randpool.py:40: RandomPool_DeprecationWarning: This application uses RandomPool, which is BROKEN in older releases.  See http://www.pycrypto.org/randpool-broken
  RandomPool_DeprecationWarning)
Hostout: Running command 'buildout' from 'collective.hostout.fabfile'
[adminuser@pruebas.mysite.org:22] put: /tmp/tmpUkJmAq -> /opt/mysite_libros/mysite-GqX47IgVCyxDrafXPyC2ew.cfg

Fatal error: put() encountered an exception while uploading '/tmp/tmpUkJmAq'

Traceback (most recent call last):
  File "/home/tzicatl/Aplicaciones/Buildout/egss/Fabric-0.9.4-py2.6.egg/fabric/operations.py", line 303, in put
    rattrs = ftp.put(lpath, _remote_path)
  File "/home/tzicatl/Aplicaciones/Buildout/egss/paramiko-1.7.6-py2.6.egg/paramiko/sftp_client.py", line 561, in put
    fr = self.file(remotepath, 'wb')
  File "/home/tzicatl/Aplicaciones/Buildout/egss/paramiko-1.7.6-py2.6.egg/paramiko/sftp_client.py", line 245, in open
    t, msg = self._request(CMD_OPEN, filename, imode, attrblock)
  File "/home/tzicatl/Aplicaciones/Buildout/egss/paramiko-1.7.6-py2.6.egg/paramiko/sftp_client.py", line 628, in _request
    return self._read_response(num)
  File "/home/tzicatl/Aplicaciones/Buildout/egss/paramiko-1.7.6-py2.6.egg/paramiko/sftp_client.py", line 675, in _read_response
    self._convert_status(msg)
  File "/home/tzicatl/Aplicaciones/Buildout/egss/paramiko-1.7.6-py2.6.egg/paramiko/sftp_client.py", line 701, in _convert_status
    raise IOError(errno.ENOENT, text)
IOError: [Errno 2] No such file


Aborting.
```

And for `deploy` the errors are the same as the first run.

I'm running collective.hostout from this git repo. What am I doing wrong?

**Comment by misaelnieto** [comment]
This issue is way too OLDDD. Closing.
